version: "3.9"
services:
  web:
    build: .
    ports:
    - "3000:3000"
    command: nodemon src/index.ts
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
