version: "3.9"
services:
  web:
    build: .
    volumes:
    - .:/node-js-blog
    ports:
    - "3000:3000"
    command: yarn run serve
    depends_on:
      - db
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_PORT=5432
    ports:
      - "5432:5432"

volumes:
  postgres_data:
